version: "2"
services:
        test:
                build: .
                command: ./wait-for test
                volumes:
                        - .:/app/
                        - /app/node_modules
                ports:
                        - 3001:3000
                depends_on:
                        - mysql-test
                networks:
                  - test-net        
                environment:
                  DATABASE_URL: mysql://hades:hades@mysql-test/hadesdb
                  DB_USERNAME: hades
                  DB_PASSWORD: hades
                  DB_NAME: hadesdb
                  DB_HOSTNAME: mysql-test
        mysql-test:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: hadespwd
                        MYSQL_DATABASE: hadesdb
                        MYSQL_USER: hades
                        MYSQL_PASSWORD: hades
                networks:
                  - test-net  
networks:
  test-net:
    driver: bridge
